# Generated by Django 5.2.12 on 2026-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField(db_index=True)),
                ('target_time', models.DateTimeField(db_index=True)),
                ('horizon_steps', models.IntegerField()),
                ('predicted_Price', models.FloatField()),
                ('model_vrs', models.CharField(default='v1', max_length=100)),
            ],
            options={
                'ordering': ['target_time'],
                'unique_together': {('prediction_time', 'target_time', 'horizon_steps')},
            },
        ),
    ]
