# Generated by Django 5.2.12 on 2026-03-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_made_at', models.DateTimeField(db_index=True)),
                ('target_time', models.DateTimeField(db_index=True)),
                ('horizon_steps', models.IntegerField()),
                ('predicted_demand_kw', models.FloatField()),
                ('model_version', models.CharField(default='v1', max_length=100)),
            ],
            options={
                'ordering': ['target_time'],
                'unique_together': {('prediction_made_at', 'target_time', 'horizon_steps')},
            },
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
