# Generated by Django 5.2.12 on 2026-03-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('actual_kw', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
