# Generated by Django 5.2.12 on 2026-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_actualdemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualdemand',
            name='market_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actualdemand',
            name='modeled_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actualdemand',
            name='actual_kw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
