# Generated by Django 5.2.12 on 2026-04-01 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_actualdemand_market_price_actualdemand_modeled_kw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thresholdconfig',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='thresholdconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='thresholdconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thresholdconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
