# Generated by Django 5.2.12 on 2026-04-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_thresholdconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('uptime_ms', models.BigIntegerField()),
                ('wh', models.IntegerField()),
                ('total_wh', models.IntegerField()),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
